version: "3.0"

services: 
  redis:
      container_name: coreplause-redis
      image: redis
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis-config/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        - coreplause-networks
      ports:
        - 6379:6379
networks:
  coreplause-networks: